### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by cartermp** [fsprojects/FAKE#2570]
@dsyme @matthid @forki 

Any thoughts on moving FAKE to fsprojects? There seems to be a "we need another maintainer to step up" problem right now and in general it feels like fsprojects is a better home for that kind of thing since it has more involved people than the `fsharp` org.

**Comment by matthid** [comment]
I'm not sure what it will break in the release and build infrastructure. So it might make it even harder for a new maintainer to step up?
Other than that I don't really have any thoughts or objections.

**Comment by dsyme** [comment]
Yes it should move. @matthid if you could fix up anything after the move that would be great

**Comment by halcwb** [comment]
I for one would be very happy with this. I also would be willing to donate if for example FAKE would be turned into a sponsored project.

**Comment by yazeedobaid** [comment]
Any thoughts on how this could be done?

**Comment by dsyme** [comment]
@matthid @forki   I'm ok with moving this to fsprojects

What's the current maintenance situation?  @matthid are you partial, low-activity maintainer?  I assume we are open to new maintainers?

Thanks

**Comment by yazeedobaid** [comment]
Yes, my company and I are both willing to support the project. 
Currently, my company is allocating 10 hours a week for me to maintain this project as a form of support.

Thanks

**Comment by dsyme** [comment]
@yazeedobaid That's great to know, thank you.  Can you email me on "dsyme AT microsoft DOT com", I need to ask a few things for checks, then we should be able to proceed with moving to fsprojects and making you a co-maintainer, at least in this repo.  I'll ask @matthid  and @forki about making releases.

**Comment by halcwb** [comment]
> @matthid @forki I'm ok with moving this to fsprojects
> 
> What's the current maintenance situation? @matthid are you partial, low-activity maintainer? I assume we are open to new maintainers?
> 
> @yazeedobaid @halcwb Are you interested in being a maintainer?
> 
> Thanks

@dsyme I have to admit that I am not qualified to maintain such a library. I did not receive any formal training as a programmer. Actually, I am a full time pediatric intensivist, with limited time for my passion, programming in F#. So, I have to disappoint you.

**Comment by dsyme** [comment]
@halcwb Thanks for letting us know! :)

@yazeedobaid did you email me? Thanks

**Comment by yazeedobaid** [comment]
@dsyme Yes I sent you an email
Thanks

**Comment by dsyme** [comment]
Anyone know why this got auto-closed

**Comment by dsyme** [comment]
I see, was because of this action that auto-marks stale issues. Hmmmm https://github.com/fsharp/FAKE/blob/release/next/.github/workflows/stale.yml

**Comment by dsyme** [comment]
@yazeedobaid I looked for your email but couldn't see it.  Could you try again please?

**Comment by yazeedobaid** [comment]
@dsyme I sent you another email
Thanks.

**Comment by rmunn** [comment]
If you want to prevent the stale-bot from closing an issue (say, because it's a discussion that should be kept open long-term), adding the `skip-stale` label should do it.

**Comment by dsyme** [comment]
Done
