### ISSUE TITLE
NUnit3 Module call to console runner fails with FileLoadException

### ISSUE THREAD

**Issue by pchinery** [fsprojects/FAKE#2600]
### Description

Suddenly, our NUnit 3 Console runner started to fail with an FileLoadException for `nunit.engine.api` with the message "Provider DLL failed to initialize correctly" (HRESULT: 0x8009001D).

This most likely happened after an update to dotnet 5.0.301. We had to update `MSBuild.StructuredLogger`, because the log format had changed. With that being the only change in our dependencies, the error now appears and the code is unchanged otherwise. So the most likely root cause is the dotnet update.

### Repro steps

I have created a sample repo which fails on multiple machines with dotnet 5.0.301. It contains two test targets. Both *should* do the same, but the manual process creation works while the NUnit module fails with the given exeception. The parameter lists are identical and even using a parameter file (like the module does) does not change the result.

* Clone https://github.com/pchinery/nunit-bug-hunt
* Ensure that dotnet 5.0.301 is installed
* run `dotnet tool restore`
* run `dotnet fake build`

### Expected behavior

The whole build script should execute successfully and both test targets should run all tests.

### Actual behavior
The target `Test2` fails with an FileLoadException for `nunit.engine.api` with the message "Provider DLL failed to initialize correctly" (HRESULT: 0x8009001D).

### Known workarounds

Calling NUnit manually (as in `Test1`) does help (for whatever reason).

**Comment by thinkbeforecoding** [comment]
having the exact same problem. Trying to run the same cmd line in the terminal succeeds.

**Comment by yazeedobaid** [comment]
> Clone https://github.com/fsharp/FAKE/issues

Can you please provide the URL for the repro repository?

For `MSBuild.StructuredLogger` we have this [PR](https://github.com/fsharp/FAKE/pull/2597) which handles the update of the structured logger.

Thanks

**Comment by pchinery** [comment]
> Can you please provide the URL for the repro repository?

Sorry, I somehow pasted the wrong URL in the description. I have updated it now and the correct URL is https://github.com/pchinery/nunit-bug-hunt

> For `MSBuild.StructuredLogger` we have this [PR](https://github.com/fsharp/FAKE/pull/2597) which handles the update of the structured logger.

The part with `MSBuild.StructuredLogger` most likely is not related to this problem. I just wanted to point out that code in our repository suddenly stopped working with no change to the code itself and only the single dependency `MSBuild.StructuredLogger` being updated.

**Comment by rosecodym** [comment]
I'm seeing this too (after an update to .NET 6 in my case).

**Comment by michaelsmithson** [comment]
I just started getting this issue as well after upgrading to .NET 6. 

For me commenting out the line "CreateProcess.withEnvironment" in the createProcess function here https://github.com/fsprojects/FAKE/blob/562dfc62301e1d553ab2b1c454997f2e009775c2/src/app/Fake.DotNet.Testing.NUnit/NUnit3.fs#L342 resolved it for me. 

I'm not really sure why this was causing the issue as I was just passing an empty list to that function.

**Comment by yazeedobaid** [comment]
@michaelsmithson Thanks a lot for the hint at that location. It indeed was the cause of the issue.
I have opened PR #2690 which has a possible fix for the issue.
Feedback is highly appreciated.

**Comment by yazeedobaid** [comment]
The fix has been released in `5.23.0` release.
