### ISSUE TITLE
Support .NET 6 Release Candidate 1

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FAKE#2604]
### Description

`fake-cli` fails when dotnet `6.0.100-rc.1.21463.6` is installed

### Repro steps

![image](https://user-images.githubusercontent.com/1197905/134565474-be9ec37d-42fa-4efa-a6da-34d9b7e4f688.png)

### Actual behavior

Failed to initialize CoreCLR, HRESULT: 0x80004005

### Known workarounds

I think CLI tool should be compiled with 

```
<RollForward>LatestMajor</RollForward>
````
as it is done in [fsdocs](https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.Formatting.CommandTool/FSharp.Formatting.CommandTool.fsproj#L8) & [fslex](https://github.com/fsprojects/FsLexYacc/blob/master/src/FsLex/fslex.fsproj#L6)

**Comment by sergey-tihon** [comment]
Issue may be not related FAKE itself.
I have uninstall latest preview of VS and many of my dotnet sdks/runtimes and reinstall latest one again to fix it.
It looks like installer issues, since nobody else complain about this issue.

**Comment by eglyph** [comment]
Please also note that even if your project is using .NET 6.0, a 3.1 version still has to be installed for paket 7.3.1. to work. If you uninstalled it, it will produce the `Failed to initialize CoreCLR, HRESULT: 0x80004005` error.
