### ISSUE TITLE
SqlPackage doesn't work with VS2022

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FAKE#2629]
### Description

OOTB SqlPackage can't be located with VS2022. This is because VS no longer resides in Program Files (x86) but Program Files.

### Known workarounds

Manually set the path yourself.

I'll raise a PR for this.

**Comment by yazeedobaid** [comment]
The fix for this issue is included in release [5.21.0](https://github.com/fsprojects/FAKE/releases/tag/5.21.0)

Thanks
