### ISSUE TITLE
Async calls make script invalid

### ISSUE THREAD

**Issue by otto-gebb** [fsprojects/FAKE#2650]
### Description

If I make a call to [ReadAsStringAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent.readasstringasync?view=net-6.0), the script fails with the following error:

> Script is not valid:
>	unknown (1,0)-(1,0): Error FS0193: The module/namespace 'System' from compilation unit 'netstandard' did not contain the namespace, module or type 'IAsyncDisposable'

### Repro steps

1. Create a file `build.fsx` with the following content:
   ```fs
   #r "paket:
   nuget Fake.Core.Target //"
   
   #if !FAKE
   #load "./.fake/build.fsx/intellisense.fsx"
   #endif
   
   open Fake.Core
   open System.Net.Http
   open System.Net.Http.Headers
   open System.Threading.Tasks
   
   let myCall (response: HttpResponseMessage) : Task<string> =
       task {
         let! content = response.Content.ReadAsStringAsync()
         return content
       }
   
   // Default target
   Target.create "Default" (fun _ ->
       Trace.trace "Hello World from FAKE"
   )
   
   // start build
   Target.runOrDefault "Default"
   ```

2. Run the script like this: `fake run build.fsx -t Default`

### Expected behavior

The script runs successfully and outputs "Hello World from FAKE".

### Actual behavior

The `fake` command outputs the following:
```
The last restore is still up to date. Nothing left to do.
Script is not valid:
	unknown (1,0)-(1,0): Error FS0193: The module/namespace 'System' from compilation unit 'netstandard' did not contain the namespace, module or type 'IAsyncDisposable'
Performance:
 - Cli parsing: 140 milliseconds
 - Packages: 56 milliseconds
 - Script compiling: 1 second
 - Script analyzing: 105 milliseconds
 - Runtime: 1 second
```

### Known workarounds

None.

### Related information 

* Operating system: tried in Arch linux and Windows with the same result (failure).
* Branch: master (I guess)
* .NET Runtime, CoreCLR or Mono Version:
   ```
   ❯ dotnet --info                
   .NET SDK (reflecting any global.json):
    Version:   6.0.100
    Commit:    9e8b04bbff
   
   Runtime Environment:
    OS Name:     arch
    OS Version:  
    OS Platform: Linux
    RID:         arch-x64
    Base Path:   /usr/share/dotnet/sdk/6.0.100/
   
   Host (useful for support):
     Version: 6.0.0
     Commit:  4822e3c3aa
   
   .NET SDKs installed:
     3.1.120 [/usr/share/dotnet/sdk]
     6.0.100 [/usr/share/dotnet/sdk]
   
   .NET runtimes installed:
     Microsoft.AspNetCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
     Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
     Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
     Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
   ```
* Version of FAKE (4.X, 5.X): 5.21.1

**Comment by yazeedobaid** [comment]
Can you please add a `global.json` file beside the script and use a Net6 SDK? 
From the error message, it seems that the runner has defaulted to Nestandard2.0 reference assemblies and they don't contain this method. It is only specified in Net5 and Net6 per the documentation of the method [ReadAsStringAsync](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcontent.readasstringasync?view=net-6.0).

**Comment by otto-gebb** [comment]
I added a `global.json` file with the following content:
```json
{
  "sdk": {
    "version": "6.0.100"
  }
}
```

And now I get a different error:

> There was a problem while setting up the environment:
> -> Could not find referenced assemblies in path: '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.0/ref/net6.0', please check installed SDK and runtime versions

**Comment by otto-gebb** [comment]
Adding a `global.json` file alongside all my build scripts could be a workaround (not a solution), but unfortunately it doesn't work.

**Comment by yazeedobaid** [comment]
Adding a `global.json` file is not a workaround, it is used to enable Net6 reference assemblies. If no `global.json` is found beside script or in another directory it will fall back to Netstandard2.0 reference assemblies. This is by design, to not introduce a breaking change.

The specified SDK version of `6.0.100` has a matching runtime version of `6.0.0` which is the one that FAKE runner resolves as in the error message: `/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.0/ref/net6.0`

However, from that directory, you have a runtime with version `6.0.1` which matches SDK version `6.0.101`

Not sure how this got mixed up! Can you please download SDK version `6.0.100` and try or download SDK version `6.0.101` and specify it in your `global.json`?

**Comment by otto-gebb** [comment]
@yazeedobaid I installed SDK `6.0.101`.
```
❯ sudo ./dotnet-install.sh --install-dir /usr/share/dotnet -channel Current -version latest
...
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.101/dotnet-sdk-6.0.101-linux-x64.tar.gz
...
❯ dotnet --info                   
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.120 [/usr/share/dotnet/sdk]
  6.0.100 [/usr/share/dotnet/sdk]
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

And added the `global.json` file:

```json
{
  "sdk": {
    "version": "6.0.101"
  }
}
```

And now the script runs successfully. Thanks for your help!

It's a bit sad that I now have to go and create a `global.json` file in a lot of places, especially considering that everything has worked fine without it for many years until now.

Is there a way to specify the runtime for FAKE (and only for FAKE) differently (e.g. an env variable or some parameter in `paket.dependencies`?

**Comment by otto-gebb** [comment]
Found another [workaround](https://github.com/eiriktsarpalis/TypeShape/blob/main/build.fsx#L5-L12):
- load packages via NuGet: `#r "nuget: Fake.Core.Target"`;
- add a code block initializing the FAKE execution context;
- run the script via `dotnet fsi ./build.fsx -t Default`.

After the adjustmets the script from the original post looks like this:

```fs
#r "nuget: Fake.Core.Target"

open Fake.Core
open System
open System.Net.Http
open System.Threading.Tasks

#if !FAKE
Environment.GetCommandLineArgs()
|> Array.skip 2
|> Array.toList
|> Fake.Core.Context.FakeExecutionContext.Create false __SOURCE_FILE__
|> Fake.Core.Context.RuntimeContext.Fake
|> Fake.Core.Context.setExecutionContext
#endif

let myCall (response: HttpResponseMessage) : Task<string> =
    task {
      let! content = response.Content.ReadAsStringAsync()
      return content
    }

// Default target
Target.create "Default" (fun _ ->
    Trace.trace "Hello World from FAKE"
)

// start build
Target.runOrDefault "Default"
```
