### ISSUE TITLE
The namespace Sql ist not defined

### ISSUE THREAD

**Issue by thomrad** [fsprojects/FAKE#2660]
### Description

Adding the Sql namespace gives me the error "The namespace Sql ist not defined" - I want to use it for the SqlServer module. https://fake.build/sql-sqlserver.html

### Repro steps

I am using fake cli version 5.22.0 with .net 6.0 sdk

```
#r "paket: 
nuget Fake.Core
nuget Fake.Core.Environment
nuget Fake.Core.Target
nuget Fake.Core.Xml
nuget Fake.IO.FileSystem
nuget Fake.Sql
//"
#load ".fake/build.fsx/intellisense.fsx"

open Fake.Sql
```

Deleting directory .fake
Deleting file build.fsx.lock

running fake build 

Installs all Dependencies / Packages including Fake.Sql 

Still doesn't know the namespace. 

### Expected behavior

open the Fake.Sql namespace without problem. 

### Actual behavior

Does not know the namespace Fake.Sql

### Known workarounds

Don't know any workaround

**Comment by thomrad** [comment]
@yazeedobaid Unfortunately those packages are not available on nuget:

There was a problem while setting up the environment:
-> Unable to retrieve package versions for 'Fake.Sql.SqlServer'

How should I retrieve that package? Via github? If so, how do let my script know, that those packages are available? I am totally new to fake and paket and beginner level f# ....

**Comment by yazeedobaid** [comment]
@thomrad package `Fake.Sql.SqlServer` is not pushed to NuGet anymore. Please try the other two packages. Here are the links for them in NuGet.
[`Fake.Sql.DacPac`](https://www.nuget.org/packages/Fake.Sql.DacPac/)
[`Fake.Sql.SqlPackage`](https://www.nuget.org/packages/Fake.Sql.SqlPackage/)

**Comment by thomrad** [comment]
@yazeedobaid Thank you, that did the trick. But unfortunately the DacPac and SqlPackage don't help. SqlServer had what I needed and that is not part of those packages. So, the only thing I can do, is to build fake on my machine and then use that SqlServer module. 

Thank's again for helping out.

**Comment by yazeedobaid** [comment]
@thomrad yes you can do that. Sorry I'm not aware of why the `SqlServer` module is not pushed to NuGet! I'll try to look and see why...
