### ISSUE TITLE
Release Notes - Conventional Changelog compatibility

### ISSUE THREAD

**Issue by akhansari** [fsprojects/FAKE#2676]
### Description

Release Notes module is not compatible with [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog).

This is an enhancement.

### Repro steps

`ReleaseNotes.load` on a file like [this](https://github.com/conventional-changelog/commitlint/blob/master/CHANGELOG.md).

### Expected behavior

Be able to parse Conventional changelogs and maybe ignore headers without version.

### Actual behavior

System.Exception

### Known workarounds

x

### Related information 

* FAKE v5.22

**Comment by baronfel** [comment]
There's a Changelog module as well that you may prefer to use instead of the ReleaseNotes module. I've switched many of my repos over to it (or to Ionide.KeepAChangelog directly) as a result.

**Comment by baronfel** [comment]
I mean sure, yes, but I would instead just know that if I'm using a CHANGELOG.md then I need to use the Changelog module. You have to do an explicit migration right now from the FAKE-specific ReleaseNotes format to the more general Changelog format, so I don't really see a point to trying to automatically detect the format.

**Comment by akhansari** [comment]
OK it makes sense. thank you Chet 🙏🏻

**Comment by baronfel** [comment]
If you want to migrate an existing Release Notes file, here's a one-time conversion function I made for FSAutoComplete when we moved: [fsharp/FsAutoComplete@`af81187` (#881)](https://github.com/fsharp/FsAutoComplete/pull/881/commits/af8118729e9737071c543de58223164134051fe4#diff-5ebd60ceb88910043c04c5a665d836197d7184488edcf52f590e8fcad6101519R196)

It might make sense for FAKE to have this, now that I think of it.
