### ISSUE TITLE
ReleaseNotes.load does not parse SemVer correctly v2

### ISSUE THREAD

**Issue by Freymaurer** [fsprojects/FAKE#2683]
### Description

Issue #2557 is still not fixed. I could propably fix it and do a PR, but i need to know if this is wanted, as i see multiple stale PRs.

@forki

**Comment by yazeedobaid** [comment]
@Freymaurer yes, please. That would be great

**Comment by Freymaurer** [comment]
Is there already a planned date when the next FAKE release will happen?

**Comment by yazeedobaid** [comment]
I'm planning for another alpha release today or tomorrow.
