### ISSUE TITLE
Update Paket.Core to support .NET 7

### ISSUE THREAD

**Issue by mk185147** [fsprojects/FAKE#2708]
### Description

Today Fake uses Paket.Core 6.2.1 that doesn't support .NET 7. There already exists a stable package of Paket.Core 7.1.5 that works fine with .NET 7.

### Repro steps

If you have paket.lock file that was created for .NET 7 running dotnet fake build can fail with error:
```
here was a problem while setting up the environment:
-> Error during parsing of 'C:\Users\mk185147\source\repos\ncr-swt-cfr\site-trust\paket.lock'.
-> invalid parameter 'net7.0' after >= or < in '== net7.0'
```

**Comment by Thorium** [comment]
I have the same error with .NET 8:

```
There was a problem while setting up the environment:
-> Error during parsing of 'C:\git\MyProject\paket.lock'.
-> invalid parameter 'net8.0' after >= or < in '== net8.0) (== netstandard2.1)'
```
