### ISSUE TITLE
MSBuild.build adds a bad string at the end of properties

### ISSUE THREAD

**Issue by akhansari** [fsprojects/FAKE#2738]
### Description

MSBuild.build adds always a bad string at the end of properties.

Like: `/p:foo=bar<fun:quoteString@686>`

### Repro steps

```fsharp
path
|> MSBuild.build (fun o ->
    { o with
        Properties = [
            "Configuration", "Release"
            "DeployOnBuild", "True"
            "DeployDefaultTarget", "WebPublish"
            "WebPublishMethod", "FileSystem"
            "PublishUrl", __SOURCE_DIRECTORY__ </> "publish" </> name
            "Version", version
        ]
    })
```

### Expected behavior

"C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe" MyProject.csproj /m /nodeReuse:False /p:RestorePackages=False /p:Configuration=Release /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:PublishUrl=publish%5CMyProject /p:Version=1.1.0-beta

### Actual behavior

"C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe" MyProject.csproj /m /nodeReuse:False /p:RestorePackages=False /p:Configuration=Release /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:PublishUrl=publish%5CMyProject /p:Version=1.1.0-beta`<fun:quoteString@686>`

### Known workarounds

Add a dummy property at the end.

### Related information 

* Windows 11
* .NET 6
* FAKE 6

**Comment by 0x53A** [comment]
The issue is here:

https://github.com/fsprojects/FAKE/blob/4c22f110105018f85c359c179007c402e4d9d1a1/src/app/Fake.DotNet.MSBuild/MSBuild.fs#L684-L687

because ``appendQuotedIfNotNull`` works differently than expected. The first parameter gets passed "Some" as a function, which doesn't make any sense.

![image](https://user-images.githubusercontent.com/4236651/224295544-92e279d7-a7c4-4e4b-a80f-09dc204d6273.png)

**Comment by plainionist** [comment]
This issue is open since months, without fix (which is even available as PR) MsBuild module is effectively unusable.
can one pls merge the PR and release a "hot fix"?
thx

**Comment by DanielRowe1** [comment]
Is there going to be a release which included this fix?

**Comment by voronoipotato** [comment]
@xperiandri @Numpsy  are we going to see a release? It would be really helpful if we could get one.

**Comment by xperiandri** [comment]
Do we have the release notes file updated?
https://fake.build/guide/contributing.html#Release-Process
If so I'm ready to release.

**Comment by Numpsy** [comment]
> Do we have the release notes file updated? https://fake.build/guide/contributing.html#Release-Process If so I'm ready to release.

Does the shortHash function added in #2752 / #2770 need adding to the relase note?

**Comment by voronoipotato** [comment]
> Do we have the release notes file updated? https://fake.build/guide/contributing.html#Release-Process If so I'm ready to release.
If its between working code and having notes, I'd say I'd prefer to have a release. Right now my team is pretty confused why they can't use msbuild without some dummy field. If we can update the notes too that sounds neat but we shouldn't let that completely block us.

**Comment by xperiandri** [comment]
@Numpsy  Let's add that and I release
