### ISSUE TITLE
[REGRESSION] FAKE 6.1.0 fails with dotnet preview versions

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/FAKE#2803]
### Description

Upgrading the AltCover build from v6.0.0 to v6.1.0, the first use of `Fake.DotNet.DotNet.exec` fails when parsing the version string in `global.json`. The same is true for other APIs, like ` DotNet.restore`

### Repro steps

1. Install SDK 9.0.100-preview.6.24328.19
2. Invoke it with a global.json like
```
{
  "sdk": {
    "version": "9.0.100-preview.6.24328.19",
    "rollForward": "latestMinor"
  }
}
```
3. Run a command with `DotNet.exec`

### Expected behavior

It just works, i.e. unchanged since v 6.0.0

### Actual behavior

Exception thrown
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'AltCover.Targets' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<StartupCode$build>.$Targets' threw an exception.
 ---> System.Exception: Could not parse `sdk.version` from global.json at 'C:\Users\email\Documents\Github\altcover\global.json': Version string portion was too short or too long. (Parameter 'input')
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at Fake.DotNet.DotNet.tryGetSDKVersionFromGlobalJsonDir(String startDir) in D:\a\FAKE\FAKE\src\app\Fake.DotNet.Cli\DotNet.fs:line 77
   at Fake.DotNet.DotNet.Options.Create() in D:\a\FAKE\FAKE\src\app\Fake.DotNet.Cli\DotNet.fs:line 546
   at Fake.DotNet.DotNet.exec(FSharpFunc`2 buildOptions, String command, String args) in D:\a\FAKE\FAKE\src\app\Fake.DotNet.Cli\DotNet.fs:line 772
   at <StartupCode$build>.$Targets..cctor() in C:\Users\email\Documents\Github\altcover\Build\targets.fs:line 174
```

### Known workarounds

Revert to 6.0.0

### Related information 

* Operating system - Windows 11
* Branch - using the 6.1.0 release from NuGet
* .NET Runtime, CoreCLR or Mono Version - dotnet SDK 9.0.100-preview.6.24328.19
* Indications of severity - complete stopper for pre-release development
* Version of FAKE (4.X, 5.X, 6.x) - 6.1.0

**Comment by SteveGilham** [comment]
Parsing out the underlying version would be something like in [Fake.DotNet.Cli/DotNet.fs, line 73](https://github.com/fsprojects/FAKE/blob/681f31abbf9007d70bb6d97a46ab1fd1793300e1/src/app/Fake.DotNet.Cli/DotNet.fs#L73) to put

`let versionValue = (version.Value.ToString().Split("-preview"))[0]`

but when used to determine an SDK file path, then the correct action is to use the `global.json` value as it stands, and only throw when files are not found.

**Comment by SteveGilham** [comment]
Having had time to reflect on this at leisure -

Firstly, I was forgetting earlier that we also have release candidate builds, like last year's `"8.0.100-rc.1.23463.5`, so the correct general version extraction would be 

`let versionValue = (version.Value.ToString().Split('-'))[0]`

Secondly, chasing up the call chain to [the definition of `Options.Create`](https://github.com/fsprojects/FAKE/blob/681f31abbf9007d70bb6d97a46ab1fd1793300e1/src/app/Fake.DotNet.Cli/DotNet.fs#L545), this is trying to compose a file path, so shouldn't be extracting the version from the `global.json` as other than a literal string.

The correct fix, therefore is to simply delete [line 74](https://github.com/fsprojects/FAKE/blob/681f31abbf9007d70bb6d97a46ab1fd1793300e1/src/app/Fake.DotNet.Cli/DotNet.fs#L74), thus simplifying the match expression to 
```fsharp
                match sdk.Property("version") with
                | null -> None
                | version ->
                    Some (version.Value.ToString())
```

**Comment by Numpsy** [comment]
refs #2757 I think? (I don't know why the ```Version.Parse``` was added as well as the null check)

**Comment by xperiandri** [comment]
Try 6.1.1

**Comment by SteveGilham** [comment]
That resolves the issue.  Thank you!
