### ISSUE TITLE
Cannot target to .NET8 by FAKE_SDK_RESOLVER_CUSTOM_DOTNET_VERSION

### ISSUE THREAD

**Issue by hglee** [fsprojects/FAKE#2817]
### Description

When targeting against .NET8 by specifying FAKE_SDK_RESOLVER_CUSTOM_DOTNET_VERSION, Fake assembly cannot be referenced.

### Repro steps

1. Download CLI runner: fake-dotnetcore-win7-x64.zip 

2. Run new command window
3. Set env by command : `set FAKE_SDK_RESOLVER_CUSTOM_DOTNET_VERSION=8.0`
4. Run command: `fake.exe -vv run Build.fsx `

### Expected behavior

I expected it to build without any problems

### Actual behavior

The error occurs as follows(the full log and script are attached):

```
Script is not valid, see standard error for details.

Script is not valid:

	C:\tmp\test611\build.fsx (5,5)-(5,9): Error FS0039: 'Fake' 네임스페이스 또는 모듈이 정의되지 않았습니다.

	C:\tmp\test611\build.fsx (6,5)-(6,9): Error FS0039: 'Fake' 네임스페이스 또는 모듈이 정의되지 않았습니다.

	C:\tmp\test611\build.fsx (8,0)-(8,6): Error FS0039: 'Target' 값, 네임스페이스, 형식 또는 모듈이 정의되지 않았습니다.

	C:\tmp\test611\build.fsx (12,0)-(12,6): Error FS0039: 'Target' 값, 네임스페이스, 형식 또는 모듈이 정의되지 않았습니다.
```

[20240903.txt](https://github.com/user-attachments/files/16847385/20240903.txt)
[Build.txt](https://github.com/user-attachments/files/16847388/Build.txt)

### Related information 

* Operating system : Windows11
* Branch
* .NET Runtime, CoreCLR or Mono Version : .NET 8
* Indications of severity
* Version of FAKE (4.X, 5.X, 6.x) : v6.1.1
* (if performance issue) Performance information, links to performance testing scripts

**Comment by Thorium** [comment]
Try with latest in 6.1.3.

**Comment by hglee** [comment]
It works, thanks!

FYI, it only works without FAKE_SDK_RESOLVER_CUSTOM_DOTNET_VERSION. I got same error as before if I set FAKE_SDK_RESOLVER_CUSTOM_DOTNET_VERSION to 8.0 .
